import type { Workspace, Lead, Deal, Activity, Member } from "@/types"

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: "ws-1",
    name: "Acme Corp",
    slug: "acme-corp",
    plan: "pro",
    stripe_customer_id: null,
    stripe_subscription_id: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "ws-2",
    name: "Freelance Projetos",
    slug: "freelance",
    plan: "free",
    stripe_customer_id: null,
    stripe_subscription_id: null,
    created_at: "2024-03-15T00:00:00Z",
  },
]

export const MOCK_CURRENT_WORKSPACE = MOCK_WORKSPACES[0]

export const MOCK_USER = {
  id: "user-1",
  name: "Ana Silva",
  email: "ana.silva@acmecorp.com",
  initials: "AS",
}

export const MOCK_MEMBERS: (Member & { name: string; initials: string })[] = [
  {
    id: "member-1",
    workspace_id: "ws-1",
    user_id: "user-1",
    role: "admin",
    invited_email: null,
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    name: "Ana Silva",
    initials: "AS",
  },
  {
    id: "member-2",
    workspace_id: "ws-1",
    user_id: "user-2",
    role: "member",
    invited_email: null,
    status: "active",
    created_at: "2024-01-15T00:00:00Z",
    name: "Bruno Costa",
    initials: "BC",
  },
  {
    id: "member-3",
    workspace_id: "ws-1",
    user_id: "user-3",
    role: "member",
    invited_email: null,
    status: "active",
    created_at: "2024-02-01T00:00:00Z",
    name: "Carla Mendes",
    initials: "CM",
  },
]

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    workspace_id: "ws-1",
    name: "Rafael Oliveira",
    email: "rafael.oliveira@techstart.com.br",
    phone: "(11) 99123-4567",
    company: "TechStart Ltda",
    role: "CTO",
    status: "new",
    owner_id: "user-1",
    created_at: "2024-04-01T10:00:00Z",
  },
  {
    id: "lead-2",
    workspace_id: "ws-1",
    name: "Mariana Ferreira",
    email: "mariana@inova.io",
    phone: "(21) 98765-4321",
    company: "Inova Soluções",
    role: "CEO",
    status: "contacted",
    owner_id: "user-2",
    created_at: "2024-04-03T14:30:00Z",
  },
  {
    id: "lead-3",
    workspace_id: "ws-1",
    name: "Lucas Pereira",
    email: "lucas.pereira@construtora.com",
    phone: "(31) 97654-3210",
    company: "Construtora Horizonte",
    role: "Diretor Financeiro",
    status: "qualified",
    owner_id: "user-1",
    created_at: "2024-04-05T09:15:00Z",
  },
  {
    id: "lead-4",
    workspace_id: "ws-1",
    name: "Fernanda Santos",
    email: "fernanda.santos@varejista.com.br",
    phone: "(41) 96543-2109",
    company: "Varejista Express",
    role: "Gerente de Operações",
    status: "unqualified",
    owner_id: "user-3",
    created_at: "2024-04-07T16:00:00Z",
  },
  {
    id: "lead-5",
    workspace_id: "ws-1",
    name: "Diego Almeida",
    email: "diego@agenciadigital.com",
    phone: "(51) 95432-1098",
    company: "Agência Digital Sul",
    role: "Sócio-fundador",
    status: "converted",
    owner_id: "user-2",
    created_at: "2024-04-10T11:45:00Z",
  },
  {
    id: "lead-6",
    workspace_id: "ws-1",
    name: "Camila Rodrigues",
    email: "camila.rodrigues@logistica.com.br",
    phone: "(62) 94321-0987",
    company: "LogFast Transporte",
    role: "Coordenadora Comercial",
    status: "new",
    owner_id: "user-1",
    created_at: "2024-04-12T08:30:00Z",
  },
  {
    id: "lead-7",
    workspace_id: "ws-1",
    name: "Thiago Nascimento",
    email: "thiago@saas.dev",
    phone: "(85) 93210-9876",
    company: "SaaS.dev",
    role: "Product Manager",
    status: "contacted",
    owner_id: "user-3",
    created_at: "2024-04-14T13:00:00Z",
  },
]

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "call",
    description: "Ligação inicial de prospecção. Rafael demonstrou interesse no produto, pediu mais informações sobre integrações.",
    author_id: "user-1",
    date: "2024-04-02T10:00:00Z",
    created_at: "2024-04-02T10:05:00Z",
  },
  {
    id: "act-2",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "email",
    description: "Enviado e-mail com apresentação completa do produto e cases de clientes do setor de tecnologia.",
    author_id: "user-1",
    date: "2024-04-03T09:00:00Z",
    created_at: "2024-04-03T09:02:00Z",
  },
  {
    id: "act-3",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    type: "meeting",
    description: "Reunião de descoberta via Google Meet. Identificamos dor principal: falta de visibilidade no pipeline de vendas.",
    author_id: "user-2",
    date: "2024-04-04T15:00:00Z",
    created_at: "2024-04-04T15:30:00Z",
  },
  {
    id: "act-4",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    type: "note",
    description: "Mariana mencionou que o contrato atual com concorrente vence em julho. Oportunidade de abordagem em junho.",
    author_id: "user-2",
    date: "2024-04-04T16:00:00Z",
    created_at: "2024-04-04T16:00:00Z",
  },
  {
    id: "act-5",
    workspace_id: "ws-1",
    lead_id: "lead-3",
    type: "call",
    description: "Lucas confirmou orçamento disponível de R$5.000/mês. Aguardando aprovação do conselho para avançar.",
    author_id: "user-1",
    date: "2024-04-06T10:30:00Z",
    created_at: "2024-04-06T10:45:00Z",
  },
  {
    id: "act-6",
    workspace_id: "ws-1",
    lead_id: "lead-3",
    type: "email",
    description: "Proposta comercial enviada com 3 cenários de implementação. Prazo de resposta: 5 dias úteis.",
    author_id: "user-1",
    date: "2024-04-08T14:00:00Z",
    created_at: "2024-04-08T14:05:00Z",
  },
  {
    id: "act-7",
    workspace_id: "ws-1",
    lead_id: "lead-5",
    type: "meeting",
    description: "Reunião de fechamento. Diego assinou o contrato anual. Onboarding agendado para semana que vem.",
    author_id: "user-2",
    date: "2024-04-11T10:00:00Z",
    created_at: "2024-04-11T11:00:00Z",
  },
  {
    id: "act-8",
    workspace_id: "ws-1",
    lead_id: "lead-4",
    type: "call",
    description: "Fernanda informou que a empresa não tem budget para novos softwares no momento. Retornar em Q3.",
    author_id: "user-3",
    date: "2024-04-08T16:00:00Z",
    created_at: "2024-04-08T16:10:00Z",
  },
]

export const MOCK_DEALS: Deal[] = [
  {
    id: "deal-1",
    workspace_id: "ws-1",
    lead_id: "lead-3",
    title: "Licença Enterprise - Construtora Horizonte",
    value: 5000,
    stage: "proposal_sent",
    owner_id: "user-1",
    deadline: "2024-05-01T00:00:00Z",
    created_at: "2024-04-08T00:00:00Z",
  },
  {
    id: "deal-2",
    workspace_id: "ws-1",
    lead_id: "lead-5",
    title: "Plano Pro Anual - Agência Digital Sul",
    value: 2400,
    stage: "closed_won",
    owner_id: "user-2",
    deadline: "2024-04-15T00:00:00Z",
    created_at: "2024-04-10T00:00:00Z",
  },
  {
    id: "deal-3",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    title: "Migração de sistema - Inova Soluções",
    value: 8500,
    stage: "negotiation",
    owner_id: "user-2",
    deadline: "2024-06-30T00:00:00Z",
    created_at: "2024-04-05T00:00:00Z",
  },
]
